name: CI/CD Pipeline

on:
  push:
    branches:
      - 'release/*'
    tags:
      - v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Check out Branch
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL'
          exit-code: 1
          
      - name: Send custom JSON data to Slack workflow
        if: ${{ success() }}
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Scan failed - Xena",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "test"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Notification to Slack (Failed)
        if: ${{ failure() }}
        run: 
          echo "FAILURE"