name: CI/CD Pipeline

on:
  push:
    branches:
      - 'release/*'
    tags:
      - v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Check out Branch
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL'
          exit-code: 1
      
      - name: Send Notification to Slack (Success)
        if: ${{ success() }}
        run: 
          echo "SUCCESS"

      - name: Send Notification to Slack (Failed)
        if: ${{ failure() }}
        run: 
          echo "FAILURE"
          
