name: CI/CD Pipeline

on:
  push:
    branches:
      - 'release/*'
    tags:
      - v[0-9]+.[0-9]+

jobs:
  #scan:
    # check out
    # run trivy
    # if success -> send slack notif, proceed to docker + cosign
    # if failure -> send notif and upload report 

  build:

    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Check out Branch
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'  
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          format: 'table'
          output: 'trivy-report.txt'
      
          
      - name: Send custom JSON data to Slack workflow
        if: ${{ success()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'submission'
          SLACK_COLOR: ${{ job.status }} 
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: '*Name*: Xena Lim Pin Ying\n
            *Metriculation* : A0205823L\n
            *Email*: xenalimpinying@gmail.com\n
            *Git*: https://github.com/xlpy/go-fortune\n
            *Image*: https://hub.docker.com/r/xenalimpinying/go-fortune/'
          SLACK_TITLE: 'Image build and signed'
          SLACK_USERNAME: Xena
          ENABLE_ESCAPES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        
      - name: Send Failure Notification to Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'submission'
          SLACK_COLOR: ${{ job.status }} 
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: 'Scan failed - Xena'
          SLACK_USERNAME: Xena
          ENABLE_ESCAPES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Notification to Slack (Failed)
        if: ${{ failure() }}
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-report.txt'
          initial_comment: 'Scan report by Xena'
            
      - name: Set up QEMU
        if: ${{ steps.trivy.outcome == 'success' }}
        id: docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.trivy.outcome == 'success' }}
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        if: ${{ steps.trivy.outcome == 'success' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push to Docker 
        if: ${{ steps.trivy.outcome == 'success' }} 
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          push: true
          tags: xenalimpinying/go-fortune:${{ github.sha }}

      - name: Install cosign
        if: ${{ steps.trivy.outcome == 'success' }}
        uses: sigstore/cosign-installer@2.2.0
        with:
          cosign-release: 'v2.2.0'

      - name: Sign image with a key
        if: ${{ steps.trivy.outcome == 'success' }}
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          TAGS: xenalimpinying/go-fortune:${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

        
        

        

      




        



      
    


        
        
